name: test3

on:
  workflow_run:
    workflows: ["test2","test2-1"]
    types:
      - completed

jobs:
  preview:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - run: echo 1
      - run: ls -a 
      - run: echo $github.event.workflow_run.conclusion